version: '3.3'

services:
  db:
    image: postgres:15
    container_name: db-postgres-parser
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: parser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./scripts/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart:
      unless-stopped

  parser:
    image: parser-xml:1.0
    container_name: parser-xml
    ports:
      - 8080
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/output
    command: ["export", "./app/output/data.xml"]
    depends_on:
      - db

networks:
  default:
    driver: bridge